// Every icon in the book comes from the Hugeicons free set (MIT, stroke-rounded),
// under a name that says what it is for. Render with <Icon icon={…} /> from
// '$lib/components/ui/Icon.svelte'. Only the icons named here are bundled.
export {
	Menu02Icon as MenuIcon,
	LeftToRightListBulletIcon as ContentsIcon,
	SidebarLeftIcon as SidebarIcon,
	Search01Icon as SearchIcon,
	Cancel01Icon as CloseIcon,
	ArrowDown01Icon as ChevronDownIcon,
	ArrowRight01Icon as ChevronRightIcon,
	ArrowLeft01Icon as ChevronLeftIcon,
	ArrowRight02Icon as ArrowRightIcon,
	ArrowLeft02Icon as ArrowLeftIcon,
	Tick02Icon as VisitedIcon,
	Tick02Icon as CheckIcon,
	Cancel01Icon as CrossIcon,
	Refresh01Icon as ResetIcon,
	RotateLeft01Icon as RotateLeftIcon,
	RotateRight01Icon as RotateRightIcon,
	ShuffleIcon,
	Undo02Icon as UndoIcon,
	TextClearIcon as ClearIcon,
	ArrowShrink02Icon as TightenIcon,
	Cursor01Icon as HintIcon,
	Touch01Icon as TapIcon,
	PlayIcon,
	PauseIcon,
	MinusSignIcon as MinusIcon,
	PlusSignIcon as PlusIcon,
	Clock01Icon as ClockIcon,
	// reading list
	BookOpen01Icon as BookIcon,
	File02Icon as PaperIcon,
	Note01Icon as NotesIcon,
	PlayCircleIcon as VideoIcon,
	Globe02Icon as WebIcon,
	CursorMagicSelection02Icon as InteractiveIcon,
	// callouts
	Book02Icon as DefinitionIcon,
	CheckmarkBadge02Icon as TheoremIcon,
	Note02Icon as ExampleIcon,
	BulbIcon as IntuitionIcon,
	Key01Icon as KeyIdeaIcon,
	Alert02Icon as WarningIcon,
	InformationCircleIcon as RemarkIcon,
	QuillWrite01Icon as HistoryIcon,
	CheckListIcon as RecapIcon,
	HelpCircleIcon as QuestionIcon,
	SigmaIcon as NotationIcon,
	Telescope01Icon as AheadIcon,
	PencilEdit01Icon as ExerciseIcon,
	// pages
	ThreeDRotateIcon as InteractIcon,
	Stairs01Icon as StepsIcon,
	Route01Icon as MapIcon,
	Github01Icon as GithubIcon
} from '@hugeicons/core-free-icons';
