// Small, exact helpers for relations on a finite set {0, …, n−1}.
// A relation is stored as a boolean matrix: M[i][j] === true means "i ∼ j".

export type Matrix = boolean[][];

export function emptyRelation(n: number): Matrix {
	return Array.from({ length: n }, () => Array<boolean>(n).fill(false));
}

export function fromPredicate(n: number, rel: (i: number, j: number) => boolean): Matrix {
	return Array.from({ length: n }, (_, i) => Array.from({ length: n }, (_, j) => rel(i, j)));
}

export function cloneRelation(M: Matrix): Matrix {
	return M.map((row) => row.slice());
}

/** Reflexive: every element is related to itself. Returns the elements that are not. */
export function checkReflexive(M: Matrix): { ok: boolean; missing: number[] } {
	const missing: number[] = [];
	for (let i = 0; i < M.length; i++) if (!M[i][i]) missing.push(i);
	return { ok: missing.length === 0, missing };
}

/** Symmetric: i ∼ j forces j ∼ i. Returns the first offending pair (i, j) with i ∼ j but not j ∼ i. */
export function checkSymmetric(M: Matrix): { ok: boolean; bad: [number, number] | null } {
	for (let i = 0; i < M.length; i++)
		for (let j = 0; j < M.length; j++) if (M[i][j] && !M[j][i]) return { ok: false, bad: [i, j] };
	return { ok: true, bad: null };
}

/**
 * Transitive: i ∼ j and j ∼ k force i ∼ k.
 * Returns the first offending triple (i, j, k) with i ∼ j, j ∼ k but not i ∼ k.
 */
export function checkTransitive(M: Matrix): { ok: boolean; bad: [number, number, number] | null } {
	const n = M.length;
	for (let i = 0; i < n; i++)
		for (let j = 0; j < n; j++) {
			if (!M[i][j]) continue;
			for (let k = 0; k < n; k++) if (M[j][k] && !M[i][k]) return { ok: false, bad: [i, j, k] };
		}
	return { ok: true, bad: null };
}

export function isEquivalence(M: Matrix): boolean {
	return checkReflexive(M).ok && checkSymmetric(M).ok && checkTransitive(M).ok;
}

/**
 * The equivalence relation generated by M: the smallest equivalence relation
 * containing every pair of M. (Glue i and j whenever i ∼ j, in either direction,
 * then take everything that is connected by a chain of glue.)
 */
export function equivalenceClosure(M: Matrix): Matrix {
	const n = M.length;
	const parent = Array.from({ length: n }, (_, i) => i);
	const find = (x: number): number => (parent[x] === x ? x : (parent[x] = find(parent[x])));
	for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) if (M[i][j]) parent[find(i)] = find(j);
	return fromPredicate(n, (i, j) => find(i) === find(j));
}

/** The classes of an equivalence relation, each sorted, ordered by smallest member. */
export function classesOf(M: Matrix): number[][] {
	const n = M.length;
	const seen = new Set<number>();
	const out: number[][] = [];
	for (let i = 0; i < n; i++) {
		if (seen.has(i)) continue;
		const cls: number[] = [];
		for (let j = 0; j < n; j++) if (M[i][j]) cls.push(j);
		if (!cls.includes(i)) cls.unshift(i);
		cls.forEach((j) => seen.add(j));
		out.push(cls.sort((a, b) => a - b));
	}
	return out;
}

/** Remainder of x on division by m, always in {0, …, m−1} (also for negative x). */
export function mod(x: number, m: number): number {
	return ((x % m) + m) % m;
}

// ── necklaces: colourings of the 4 corners of a square, up to rotation ─────

/** Rotate a 4-bead colouring (bits b0..b3, clockwise) by one quarter turn. */
export function rotate4(c: number): number {
	return ((c << 1) | (c >> 3)) & 15;
}

/** The orbit of colouring c under rotations, sorted. */
export function necklaceClass(c: number): number[] {
	const s = new Set<number>();
	let x = c;
	for (let k = 0; k < 4; k++) {
		s.add(x);
		x = rotate4(x);
	}
	return [...s].sort((a, b) => a - b);
}

/** All 16 two-colour colourings of a square's corners, sorted into rotation classes. */
export function necklaceClasses(): number[][] {
	const seen = new Set<number>();
	const out: number[][] = [];
	for (let c = 0; c < 16; c++) {
		if (seen.has(c)) continue;
		const cls = necklaceClass(c);
		cls.forEach((x) => seen.add(x));
		out.push(cls);
	}
	return out;
}

// ── well-definedness on ℤ/n ────────────────────────────────────────────────

export interface Rule {
	id: string;
	/** plain label for buttons */
	label: string;
	/** TeX for the rule, in terms of a representative x */
	tex: string;
	/** the output for representative x, as a comparable string */
	out: (x: number, n: number) => string;
	/** TeX of the output for representative x */
	outTeX: (x: number, n: number) => string;
}

export const rules: Rule[] = [
	{
		id: 'mod2',
		label: 'remainder mod 2',
		tex: String.raw`[x] \mapsto x \bmod 2`,
		out: (x) => String(mod(x, 2)),
		outTeX: (x) => String(mod(x, 2))
	},
	{
		id: 'mod3',
		label: 'remainder mod 3',
		tex: String.raw`[x] \mapsto x \bmod 3`,
		out: (x) => String(mod(x, 3)),
		outTeX: (x) => String(mod(x, 3))
	},
	{
		id: 'mod4',
		label: 'remainder mod 4',
		tex: String.raw`[x] \mapsto x \bmod 4`,
		out: (x) => String(mod(x, 4)),
		outTeX: (x) => String(mod(x, 4))
	},
	{
		id: 'double',
		label: 'double it',
		tex: String.raw`[x] \mapsto [2x]`,
		out: (x, n) => String(mod(2 * x, n)),
		outTeX: (x, n) => `[${mod(2 * x, n)}]`
	},
	{
		id: 'square',
		label: 'square it',
		tex: String.raw`[x] \mapsto [x^2]`,
		out: (x, n) => String(mod(x * x, n)),
		outTeX: (x, n) => `[${mod(x * x, n)}]`
	},
	{
		id: 'itself',
		label: 'the number x itself',
		tex: String.raw`[x] \mapsto x`,
		out: (x) => String(x),
		outTeX: (x) => (x < 0 ? `{-${-x}}` : String(x))
	}
];

/** Representatives of [k] in ℤ/n shown by the tester: k − n, k, k + n, k + 2n. */
export function representatives(k: number, n: number): number[] {
	return [k - n, k, k + n, k + 2 * n];
}

/**
 * Check a rule on ℤ/n by sampling representatives of every class.
 * (For the rules above this sampling is decisive: each output depends only on x mod lcm(n, m),
 * and the sampled representatives already disagree whenever the rule fails.)
 */
export function checkRule(rule: Rule, n: number): { ok: boolean; badClass: number | null } {
	for (let k = 0; k < n; k++) {
		const outs = new Set(representatives(k, n).map((x) => rule.out(x, n)));
		if (outs.size > 1) return { ok: false, badClass: k };
	}
	return { ok: true, badClass: null };
}
