import { describe, expect, it } from 'vitest';
import { SimplicialComplex } from '$lib/math/complex';
import { homology, groupName, Z2HomologyBasis } from '$lib/math/homology';
import * as C from '../homology-groups/complexes';
import { chainOf, loopChain, inRationalSpan, addChains } from '../homology-groups/chains';
import { predictedModP } from './spaces';

const names = (K: SimplicialComplex) => homology(K, 'Z').map((g) => groupName(g));

describe('§3.4 claims', () => {
	it('Möbius band: β = 2m − ∂(Σ [i, i+1, i+2])', () => {
		const M = C.mobiusBand().K;
		const m = loopChain(M, [0, 1, 2, 3, 4]);
		const beta = loopChain(M, [0, 2, 4, 1, 3]);
		const tris = chainOf(
			M,
			2,
			[0, 1, 2, 3, 4].map((i) => [i, (i + 1) % 5, (i + 2) % 5])
		);
		const d = M.boundary(2, tris);
		expect(addChains(m.map((x) => 2 * x), d, -1)).toEqual(beta);
		// and m itself is not a boundary (H₁ = ℤ generated by m)
		expect(inRationalSpan(M.boundaryMatrix(2), m)).toBe(false);
	});
	it('punctured torus and punctured Klein bottle both have H = ℤ, ℤ², 0', () => {
		for (const ex of [C.torusGrid(), C.kleinGrid()]) {
			const keep = ex.K.simplices[2].filter((t) => t.join() !== '0,1,4');
			expect(names(new SimplicialComplex(keep))).toEqual(['ℤ', 'ℤ²', '0']);
		}
	});
	it('ℝP²: every non-face 3-cycle (projective line) represents the class of c', () => {
		const P = C.projectivePlane();
		const K = P.K;
		const H = new Z2HomologyBasis(K, 1, [loopChain(K, [4, 5, 6]).flatMap((x, i) => (x ? [i] : []))]);
		expect(H.rank).toBe(1);
		const faces = new Set(K.simplices[2].map((t) => t.join()));
		let lines = 0;
		for (let a = 1; a <= 6; a++)
			for (let b = a + 1; b <= 6; b++)
				for (let c = b + 1; c <= 6; c++) {
					if (faces.has([a, b, c].join())) continue;
					lines++;
					const z = loopChain(K, [a, b, c]).flatMap((x, i) => (x ? [i] : []));
					expect(H.classOf(z)).toEqual([1]);
				}
		expect(lines).toBe(10);
	});
	it('the coefficient exercise: H = ℤ, ℤ ⊕ ℤ/4 ⊕ ℤ/3, 0', () => {
		const H = [
			{ rank: 1, torsion: [] },
			{ rank: 1, torsion: [3, 4] },
			{ rank: 0, torsion: [] }
		];
		expect(predictedModP(H, 2)).toEqual([1, 2, 1]);
		expect(predictedModP(H, 3)).toEqual([1, 2, 1]);
		expect(predictedModP(H, 5)).toEqual([1, 1, 0]);
	});
	it('genus-g non-orientable pattern on our examples: H₁ torsion is exactly one ℤ/2', () => {
		expect(homology(C.kleinGrid().K, 'Z')[1].torsion).toEqual([2]);
		expect(homology(C.projectivePlane().K, 'Z')[1].torsion).toEqual([2]);
	});
});
