// Step-by-step homology computations for the circle, disk, sphere and torus.
// Every number in the step texts is computed from the complex itself.
import { smith } from '$lib/math/linalg';
import { counterclockwise } from './flat';
import { hollowTriangle, filledTriangle, hollowTetrahedron, torusGrid, type Example } from './complexes';
import { chainOf, chainTeX, loopChain, type Chain } from './chains';

export interface PlayerStep {
	label: string;
	title: string;
	/** text with \( … \) math */
	body: string;
	/** boundary matrix to display (k), with highlights */
	matrix?: { k: number; highlightCols?: number[]; highlightRows?: number[] };
	/** picture highlights */
	chains?: { chain: Chain; color: string }[];
	triOrient?: number[];
	triFill?: { tris: number[]; color: string };
	vertexColor?: string;
	showOrientation?: boolean;
}

export interface PlayerExample {
	id: string;
	label: string;
	ex: Example;
	steps: PlayerStep[];
	/** the numbers quoted in the text, for tests */
	facts: { f: number[]; ranks: number[]; betti: number[] };
}

const rank = (M: number[][]) => (M.length && M[0].length ? smith(M).rank : 0);

function ranksOf(ex: Example) {
	const K = ex.K;
	return Array.from({ length: K.dim + 2 }, (_, k) => (k === 0 || k > K.dim ? 0 : rank(K.boundaryMatrix(k))));
}

const sumsToZero = '\\(B_0\\) consists of the 0-chains whose coefficients add up to \\(0\\)';

export function circlePlayer(): PlayerExample {
	const ex = hollowTriangle();
	const K = ex.K;
	const r = ranksOf(ex);
	const z = loopChain(K, [0, 1, 2]);
	const f = K.fVector;
	return {
		id: 'circle',
		label: 'Circle',
		ex,
		facts: { f, ranks: r, betti: [f[0] - r[0] - r[1], f[1] - r[1] - r[2]] },
		steps: [
			{
				label: 'Chains',
				title: 'The chain groups',
				body: `Three vertices and three edges, each edge oriented from its smaller label to its larger one. So \\(C_0 \\cong \\Z^{${f[0]}}\\) and \\(C_1 \\cong \\Z^{${f[1]}}\\). There are no triangles: \\(C_2 = 0\\).`,
				showOrientation: true
			},
			{
				label: '∂₁',
				title: 'The boundary matrix',
				body: `Column \\(j\\) of \\(\\partial_1\\) is the boundary of the \\(j\\)-th edge: \\(\\partial[0,1] = [1]-[0]\\), and so on. Its rank is \\(${r[1]}\\). Hover over a column to see its edge.`,
				matrix: { k: 1 },
				showOrientation: true
			},
			{
				label: 'Z₁',
				title: 'The cycles: solve \\(\\partial_1 x = 0\\)',
				body: `By rank–nullity, \\(Z_1 = \\ker\\partial_1\\) has rank \\(${f[1]} - ${r[1]} = ${f[1] - r[1]}\\). Solving gives \\(x = t\\,(1,-1,1)\\): every cycle is a multiple of \\(z = ${chainTeX(K, 1, z)}\\), the walk \\(0\\to1\\to2\\to0\\).`,
				matrix: { k: 1, highlightCols: [0, 1, 2] },
				chains: [{ chain: z, color: 'var(--gold-bright)' }]
			},
			{
				label: 'B₁',
				title: 'The boundaries: nothing is filled in',
				body: `There are no triangles, so \\(B_1 = \\im\\partial_2 = 0\\). Therefore \\(H_1 = Z_1/B_1 = Z_1 \\cong \\Z\\), generated by the class \\([z]\\): the hole.`,
				chains: [{ chain: z, color: 'var(--gold-bright)' }]
			},
			{
				label: 'H₀',
				title: 'Dimension 0',
				body: `Every 0-chain is a cycle, so \\(Z_0 = C_0 \\cong \\Z^3\\). The image of \\(\\partial_1\\) is spanned by \\([1]-[0]\\), \\([2]-[0]\\), \\([2]-[1]\\); ${sumsToZero}. Hence \\(H_0 = \\Z^3/B_0 \\cong \\Z\\): all vertices are homologous, and the class of a 0-chain is the sum of its coefficients.`,
				matrix: { k: 1 },
				vertexColor: 'var(--gold-bright)'
			},
			{
				label: 'Result',
				title: 'The answer',
				body: `\\(H_0 \\cong \\Z\\), \\(H_1 \\cong \\Z\\). Betti numbers \\(b_0 = ${f[0]} - 0 - ${r[1]} = 1\\) and \\(b_1 = ${f[1]} - ${r[1]} - 0 = 1\\): one piece, one hole.`,
				chains: [{ chain: z, color: 'var(--gold-bright)' }],
				vertexColor: 'var(--gold-bright)'
			}
		]
	};
}

export function diskPlayer(): PlayerExample {
	const ex = filledTriangle();
	const K = ex.K;
	const r = ranksOf(ex);
	const z = loopChain(K, [0, 1, 2]);
	const f = K.fVector;
	return {
		id: 'disk',
		label: 'Disk',
		ex,
		facts: { f, ranks: r, betti: [f[0] - r[0] - r[1], f[1] - r[1] - r[2], f[2] - r[2] - r[3]] },
		steps: [
			{
				label: 'Chains',
				title: 'The chain groups',
				body: `The same three vertices and edges, plus one triangle \\([0,1,2]\\): \\(C_0 \\cong \\Z^3\\), \\(C_1 \\cong \\Z^3\\), \\(C_2 \\cong \\Z\\).`,
				showOrientation: true,
				triOrient: [1]
			},
			{
				label: 'Z₁',
				title: 'The cycles are unchanged',
				body: `\\(\\partial_1\\) is the same matrix as for the circle, so \\(Z_1 \\cong \\Z\\) is still generated by \\(z = ${chainTeX(K, 1, z)}\\).`,
				matrix: { k: 1 },
				chains: [{ chain: z, color: 'var(--gold-bright)' }]
			},
			{
				label: '∂₂',
				title: 'But now there is something to fill',
				body: `\\(\\partial_2[0,1,2] = [1,2]-[0,2]+[0,1] = z\\). The single column of \\(\\partial_2\\) is exactly the cycle we found. So \\(B_1 = \\im\\partial_2 = \\Z\\,z\\).`,
				matrix: { k: 2, highlightCols: [0] },
				chains: [{ chain: z, color: 'var(--teal)' }],
				triOrient: [1],
				triFill: { tris: [0], color: 'var(--violet)' }
			},
			{
				label: 'H₁',
				title: 'Filling kills the hole',
				body: `Every cycle is a multiple of \\(z\\), and \\(z\\) is a boundary: \\(B_1 = Z_1\\). Hence \\(H_1 = Z_1/B_1 = 0\\).`,
				chains: [{ chain: z, color: 'var(--teal)' }],
				triFill: { tris: [0], color: 'var(--violet)' }
			},
			{
				label: 'H₂',
				title: 'Dimension 2',
				body: `\\(\\partial_2(n\\,[0,1,2]) = n\\,z\\), which is \\(0\\) only when \\(n = 0\\). So \\(Z_2 = 0\\) and \\(H_2 = 0\\).`,
				matrix: { k: 2 },
				triOrient: [1]
			},
			{
				label: 'Result',
				title: 'The answer',
				body: `\\(H_0 \\cong \\Z\\), \\(H_1 = 0\\), \\(H_2 = 0\\): one piece and no holes of any dimension. Betti numbers \\(1, 0, 0\\).`,
				vertexColor: 'var(--gold-bright)',
				triFill: { tris: [0], color: 'var(--violet)' }
			}
		]
	};
}

export function spherePlayer(): PlayerExample {
	const ex = hollowTetrahedron();
	const K = ex.K;
	const r = ranksOf(ex);
	const f = K.fVector;
	const eps = counterclockwise(ex.L);
	// S = all faces counterclockwise in the net = [0,1,2] − [0,1,3] + [0,2,3] − [1,2,3] = −∂[0,1,2,3]
	const S = chainOf(K, 2, [
		[0, 1, 2],
		[0, 1, 3],
		[0, 2, 3],
		[1, 2, 3]
	], [1, -1, 1, -1]);
	const square = loopChain(K, [0, 1, 3, 2]);
	const sq2 = chainOf(K, 2, [
		[0, 1, 3],
		[0, 2, 3]
	], [1, -1]);
	return {
		id: 'sphere',
		label: 'Sphere',
		ex,
		facts: { f, ranks: r, betti: [f[0] - r[0] - r[1], f[1] - r[1] - r[2], f[2] - r[2] - r[3]] },
		steps: [
			{
				label: 'Chains',
				title: 'The chain groups',
				body: `The hollow tetrahedron, unfolded into its net: fold the three outer flaps up and their tips meet at vertex \\(3\\). Four vertices, six edges, four triangles: \\(C_0 \\cong \\Z^4\\), \\(C_1 \\cong \\Z^6\\), \\(C_2 \\cong \\Z^4\\). The solid inside is *not* included.`,
				showOrientation: true
			},
			{
				label: '∂₁',
				title: 'Dimension 0 and the cycles',
				body: `\\(\\partial_1\\) is a \\(4\\times6\\) matrix of rank \\(${r[1]}\\). So \\(b_0 = 4 - 0 - ${r[1]} = 1\\) (one piece), and \\(Z_1\\) has rank \\(6 - ${r[1]} = ${6 - r[1]}\\).`,
				matrix: { k: 1 },
				showOrientation: true
			},
			{
				label: '∂₂',
				title: 'Every loop bounds',
				body: `\\(\\partial_2\\) is \\(6\\times4\\) of rank \\(${r[2]}\\), so \\(B_1\\) has rank \\(${r[2]}\\), the same as \\(Z_1\\). In fact \\(B_1 = Z_1\\) (no cycle has a multiple that bounds without bounding itself; §3.4 checks this with the Smith normal form), so \\(H_1 = 0\\). For example the square \\(0\\to1\\to3\\to2\\to0\\) is \\(\\partial([0,1,3]-[0,2,3])\\).`,
				matrix: { k: 2, highlightCols: [1, 2] },
				chains: [{ chain: square, color: 'var(--teal)' }],
				triFill: { tris: sq2.flatMap((x, i) => (x ? [i] : [])), color: 'var(--violet)' },
				triOrient: sq2
			},
			{
				label: 'Z₂',
				title: 'A 2-cycle: the whole shell',
				body: `\\(Z_2 = \\ker\\partial_2\\) has rank \\(4 - ${r[2]} = ${4 - r[2]}\\). It is generated by \\(S = ${chainTeX(K, 2, S)}\\): every face oriented counterclockwise in the net. Each edge then appears twice, with opposite signs, so \\(\\partial S = 0\\).`,
				matrix: { k: 2, highlightCols: [0, 1, 2, 3] },
				triOrient: eps,
				triFill: { tris: [0, 1, 2, 3], color: 'var(--violet)' }
			},
			{
				label: 'H₂',
				title: 'An enclosed void',
				body: `There are no 3-simplices, so \\(B_2 = \\im\\partial_3 = 0\\) and \\(H_2 = Z_2 \\cong \\Z\\), generated by \\([S]\\). If we filled in the solid tetrahedron, \\(S = -\\partial[0,1,2,3]\\) would become a boundary and \\(H_2\\) would vanish.`,
				triOrient: eps,
				triFill: { tris: [0, 1, 2, 3], color: 'var(--rose)' }
			},
			{
				label: 'Result',
				title: 'The answer',
				body: `\\(H_0 \\cong \\Z\\), \\(H_1 = 0\\), \\(H_2 \\cong \\Z\\). Betti numbers \\(1, 0, 1\\): one piece, no loops that refuse to bound, one enclosed cavity.`,
				triOrient: eps,
				vertexColor: 'var(--gold-bright)'
			}
		]
	};
}

export function torusPlayer(): PlayerExample {
	const ex = torusGrid();
	const K = ex.K;
	const r = ranksOf(ex);
	const f = K.fVector;
	const [a, b] = ex.cycles!.map((c) => c.chain);
	const eps = counterclockwise(ex.L);
	return {
		id: 'torus',
		label: 'Torus',
		ex,
		facts: { f, ranks: r, betti: [f[0] - r[0] - r[1], f[1] - r[1] - r[2], f[2] - r[2] - r[3]] },
		steps: [
			{
				label: 'Chains',
				title: 'The chain groups',
				body: `The square with opposite sides glued (labels on the rim repeat because those points are the same). \\(${f[0]}\\) vertices, \\(${f[1]}\\) edges, \\(${f[2]}\\) triangles: \\(C_0 \\cong \\Z^{${f[0]}}\\), \\(C_1 \\cong \\Z^{${f[1]}}\\), \\(C_2 \\cong \\Z^{${f[2]}}\\).`,
				showOrientation: true
			},
			{
				label: '∂₁',
				title: 'Dimension 0',
				body: `\\(\\partial_1\\) is \\(${f[0]}\\times${f[1]}\\) of rank \\(${r[1]}\\). So \\(b_0 = ${f[0]} - ${r[1]} = ${f[0] - r[1]}\\), and \\(Z_1\\) has rank \\(${f[1]} - ${r[1]} = ${f[1] - r[1]}\\). Already by hand this is tedious; a computer does it instantly.`,
				matrix: { k: 1 }
			},
			{
				label: '∂₂',
				title: 'The boundaries',
				body: `\\(\\partial_2\\) is \\(${f[1]}\\times${f[2]}\\) of rank \\(${r[2]}\\). So \\(B_1\\) has rank \\(${r[2]}\\), two short of \\(Z_1\\), and \\(Z_2\\) has rank \\(${f[2]} - ${r[2]} = ${f[2] - r[2]}\\).`,
				matrix: { k: 2 }
			},
			{
				label: 'H₁',
				title: 'Two independent holes',
				body: `\\(H_1 = Z_1/B_1\\) has rank \\(${f[1] - r[1]} - ${r[2]} = ${f[1] - r[1] - r[2]}\\). Generators: \\(a = ${chainTeX(K, 1, a)}\\) (the bottom row, gold) and \\(b = ${chainTeX(K, 1, b)}\\) (the left column, rose). So \\(H_1 \\cong \\Z^2 = \\Z[a] \\oplus \\Z[b]\\).`,
				chains: [
					{ chain: a, color: 'var(--gold-bright)' },
					{ chain: b, color: 'var(--rose)' }
				]
			},
			{
				label: 'H₂',
				title: 'The whole surface is a 2-cycle',
				body: `Orient all ${f[2]} triangles counterclockwise in the picture. Interior edges cancel in pairs, and so do the glued edges on the rim (they are traversed in opposite directions). So \\(T = \\sum \\pm t\\) is a 2-cycle, and \\(H_2 = Z_2 \\cong \\Z\\), generated by \\([T]\\).`,
				triOrient: eps,
				triFill: { tris: K.simplices[2].map((_, i) => i), color: 'var(--violet)' }
			},
			{
				label: 'Result',
				title: 'The answer',
				body: `\\(H_0 \\cong \\Z\\), \\(H_1 \\cong \\Z^2\\), \\(H_2 \\cong \\Z\\). Betti numbers \\(1, 2, 1\\): one piece, two independent loops, one enclosed cavity.`,
				chains: [
					{ chain: a, color: 'var(--gold-bright)' },
					{ chain: b, color: 'var(--rose)' }
				],
				triOrient: eps
			}
		]
	};
}

export const players = () => [circlePlayer(), diskPlayer(), spherePlayer(), torusPlayer()];
