<script lang="ts">
	// Alexander duality, seen: the complement of any knot has H₁ ≅ ℤ, generated by
	// a small loop around the knot (a meridian). A loop's class is its linking
	// number with the knot, computed here by the Gauss linking integral.
	import Scene3D, { type SceneContext, type LabelHandle } from '$lib/components/three/Scene3D.svelte';
	import Segmented from '$lib/components/ui/Segmented.svelte';
	import Slider from '$lib/components/ui/Slider.svelte';
	import TeX from '$lib/components/prose/TeX.svelte';
	import { glassMesh, glowPoint, glowTube, disposeTree } from '$lib/three/materials';
	import { disk, surfaceGeometry } from '$lib/three/surfaces';
	import { tex } from '$lib/katex/render';
	import { fovFitter } from '../cup-product/bands3d';
	import { diskPiercings, linkingNumber, loopAround, sample, trefoil, unknot, type Curve3, type V3 } from './knots';

	let knot = $state<'unknot' | 'trefoil'>('trefoil');
	let kind = $state<'meridian' | 'double' | 'far'>('meridian');
	let t0 = $state(0.12);

	const sim = $derived.by(() => {
		const K: Curve3 = knot === 'unknot' ? unknot : trefoil;
		const pts = sample(K, 500);
		// orient the loops so that the meridian links the knot positively
		const mer = sample(loopAround(K, t0, 'meridian'), 240);
		const flip = linkingNumber(pts, mer) < 0;
		const base = loopAround(K, t0, kind);
		const loop: Curve3 = flip ? (s) => base(1 - s) : base;
		const lp = sample(loop, 300);
		const lk = linkingNumber(pts, lp);
		const pierce = knot === 'unknot' ? diskPiercings(lp) : [];
		return { K, pts, loop, lp, lk, pierce };
	});
	const lkInt = $derived(Math.round(sim.lk) || 0);

	let api: { rebuild(): void } | null = null;

	function setup(ctx: SceneContext) {
		const { scene, THREE } = ctx;
		const dyn = new THREE.Group();
		scene.add(dyn);
		let labels: LabelHandle[] = [];
		let beads: { obj: InstanceType<typeof THREE.Group>; phase: number }[] = [];
		const anim = ctx.reducedMotion ? 0 : 1;
		const v3 = (p: V3) => new THREE.Vector3(p[0], p[1], p[2]);

		function rebuild() {
			disposeTree(dyn);
			dyn.clear();
			for (const l of labels) l.remove();
			labels = [];
			beads = [];
			const s = sim;
			const kc = new THREE.CatmullRomCurve3(s.pts.map(v3), true, 'centripetal');
			dyn.add(glowTube(kc, { color: 'gold', closed: true, radius: 0.075, segments: 500, haloScale: 2.4 }));
			const lc = new THREE.CatmullRomCurve3(s.lp.map(v3), true, 'centripetal');
			dyn.add(glowTube(lc, { color: 'teal', closed: true, radius: 0.028, segments: 300 }));
			for (let k = 0; k < 3; k++) {
				const b = glowPoint([0, 0, 0], { color: 'teal', size: 0.028, halo: 7 });
				dyn.add(b);
				beads.push({ obj: b, phase: k / 3 });
			}
			if (knot === 'unknot') {
				const d = glassMesh(surfaceGeometry(disk(1.35), 96, 24), { opacity: 0.42, grid: [36, 6], gridStrength: 0.16, hue: 0.55, brightness: 0.9 });
				dyn.add(d);
				for (const p of s.pierce) {
					dyn.add(glowPoint(v3(p.p), { color: 'rose', size: 0.04, halo: 9 }));
					labels.push(ctx.label(v3([p.p[0], p.p[1] + 0.22, p.p[2]]), p.sign > 0 ? '+1' : '−1', { className: 'rose sign3d' }));
				}
			}
			const kp = s.K(0.62);
			labels.push(ctx.label(v3([kp[0], kp[1] + 0.32, kp[2]]), tex('K'), { className: 'gold' }));
			const gp = s.loop(0.25);
			labels.push(ctx.label(v3([gp[0], gp[1] + 0.2, gp[2]]), tex('\\gamma'), { className: 'teal' }));
			placeBeads(0);
			ctx.invalidate();
		}
		function placeBeads(time: number) {
			for (const b of beads) {
				const u = (((b.phase + time * 0.12 * anim) % 1) + 1) % 1;
				b.obj.position.copy(v3(sim.loop(u)));
			}
		}
		const fit = fovFitter(ctx.camera, 40);
		const off = ctx.onFrame((time) => {
			fit();
			placeBeads(time);
		});
		api = { rebuild };
		rebuild();
		return {
			dispose() {
				off();
				api = null;
				for (const l of labels) l.remove();
			}
		};
	}

	$effect(() => {
		void sim;
		api?.rebuild();
	});

	const multiple = (n: number) => (n === 0 ? '0' : n === 1 ? '[m]' : n === -1 ? '-[m]' : `${n}\\,[m]`);
	const classTeX = $derived(`[\\gamma] = ${multiple(lkInt)} \\ \\in\\ H_1(\\R^3\\setminus K)\\cong\\Z`);
</script>

<div class="kl">
	<Scene3D
		{setup}
		height={430}
		animate
		camera={{ position: [0, 2.35, 4.1], fov: 40 }}
		controls={{ autoRotate: true, autoRotateSpeed: 0.4 }}
		label="A glowing gold knot (a trefoil or a round circle) with a thin teal loop near it. The loop goes once or twice around the knot's strand, or sits beside it without linking. For the round circle, a glassy disk spans it and rose points mark where the loop pierces the disk."
	/>
	<div class="read ui" aria-live="polite">
		<div class="row"><span class="k">Gauss linking integral</span><TeX tex={`\\mathrm{lk}(\\gamma, K) = ${sim.lk.toFixed(3)}`} /></div>
		<div class="row"><span class="k">class of the loop</span><TeX tex={classTeX} /></div>
		{#if knot === 'unknot'}
			<div class="row">
				<span class="k">piercings of the disk</span><TeX
					tex={sim.pierce.length ? sim.pierce.map((p) => (p.sign > 0 ? '(+1)' : '(-1)')).join('+') + ` = ${sim.pierce.reduce((a, p) => a + p.sign, 0)}` : '\\text{none} \\Rightarrow 0'}
				/>
			</div>
		{/if}
	</div>
	<div class="ctl ui">
		<Segmented
			bind:value={knot}
			label="Which knot"
			options={[
				{ value: 'trefoil', label: 'Trefoil' },
				{ value: 'unknot', label: 'Unknot (with a disk)' }
			]}
		/>
		<Segmented
			bind:value={kind}
			label="Which loop"
			options={[
				{ value: 'meridian', label: 'once around' },
				{ value: 'double', label: 'twice around' },
				{ value: 'far', label: 'not linked' }
			]}
		/>
		<Slider bind:value={t0} min={0} max={0.999} step={0.001} label="slide the loop along the knot" format={(v) => v.toFixed(2)} />
	</div>
</div>

<style>
	.kl :global(.lbl3d.sign3d) {
		font-family: var(--font-ui);
		font-weight: 700;
		font-size: 0.78rem;
		padding: 0.05rem 0.4rem;
		border-radius: 999px;
		background: rgba(20, 8, 16, 0.72);
		border: 1px solid rgba(242, 141, 182, 0.55);
		text-shadow: none;
	}
	.read {
		display: grid;
		gap: 0.3rem;
		padding: 0.7rem 1.2rem 0.6rem;
		border-top: 1px solid var(--line-faint);
		color: var(--ink-bright);
		font-size: 0.95rem;
	}
	.row {
		display: flex;
		flex-wrap: wrap;
		align-items: baseline;
		gap: 0.2rem 0.9rem;
	}
	.k {
		min-width: 11rem;
		font-size: 0.66rem;
		letter-spacing: 0.12em;
		text-transform: uppercase;
		color: var(--ink-faint);
	}
	.ctl {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: 0.7rem 1.2rem;
		padding: 0.85rem 1.2rem 1rem;
		border-top: 1px solid var(--line-faint);
		background: rgba(5, 8, 16, 0.45);
	}
</style>
