<script lang="ts">
	// Alexander duality, seen: the complement of any knot has H₁ ≅ ℤ, generated by
	// a small loop around the knot (a meridian). A loop's class is its linking
	// number with the knot, computed here by the Gauss linking integral. Grab the
	// loop and drag it along the knot: its class never changes.
	import { untrack } from 'svelte';
	import Scene3D, { type SceneContext, type LabelHandle } from '$lib/components/three/Scene3D.svelte';
	import Segmented from '$lib/components/ui/Segmented.svelte';
	import TeX from '$lib/components/prose/TeX.svelte';
	import { glassMesh, glowPoint, glowTube, disposeTree } from '$lib/three/materials';
	import { disk, surfaceGeometry } from '$lib/three/surfaces';
	import { tex } from '$lib/katex/render';
	import { fovFitter } from '../cup-product/bands3d';
	import { diskPiercings, linkingNumber, loopAround, sample, trefoil, unknot, type Curve3, type V3 } from './knots';

	let knot = $state<'unknot' | 'trefoil'>('trefoil');
	let kind = $state<'meridian' | 'double' | 'far'>('meridian');
	// where along the knot the loop sits
	let t0 = $state(0.12);

	const frac = (x: number) => x - Math.floor(x);
	const sim = $derived.by(() => {
		const K: Curve3 = knot === 'unknot' ? unknot : trefoil;
		const pts = sample(K, 500);
		// orient the loops so that the meridian links the knot positively
		const mer = sample(loopAround(K, t0, 'meridian'), 240);
		const flip = linkingNumber(pts, mer) < 0;
		const base = loopAround(K, t0, kind);
		const loop: Curve3 = flip ? (s) => base(1 - s) : base;
		const lp = sample(loop, 300);
		const lk = linkingNumber(pts, lp);
		const pierce = knot === 'unknot' ? diskPiercings(lp) : [];
		return { K, pts, loop, lp, lk, pierce };
	});
	const lkInt = $derived(Math.round(sim.lk) || 0);

	let api: { knot(): void; loop(): void } | null = null;

	function setup(ctx: SceneContext) {
		const { scene, THREE, canvas, controls } = ctx;
		const fixed = new THREE.Group();
		const dyn = new THREE.Group();
		scene.add(fixed, dyn);
		let knotLabel: LabelHandle | null = null;
		let labels: LabelHandle[] = [];
		let beads: { obj: InstanceType<typeof THREE.Group>; phase: number }[] = [];
		const anim = ctx.reducedMotion ? 0 : 1;
		const v3 = (p: V3) => new THREE.Vector3(p[0], p[1], p[2]);

		// the knot (and the unknot's disk) change only with the choice of knot
		function buildKnot() {
			disposeTree(fixed);
			fixed.clear();
			knotLabel?.remove();
			const s = sim;
			const kc = new THREE.CatmullRomCurve3(s.pts.map(v3), true, 'centripetal');
			fixed.add(glowTube(kc, { color: 'gold', closed: true, radius: 0.075, segments: 500, haloScale: 2.4 }));
			if (knot === 'unknot') {
				fixed.add(glassMesh(surfaceGeometry(disk(1.35), 96, 24), { opacity: 0.42, grid: [36, 6], gridStrength: 0.16, hue: 0.55, brightness: 0.9 }));
			}
			const kp = s.K(0.62);
			knotLabel = ctx.label(v3([kp[0], kp[1] + 0.32, kp[2]]), tex('K'), { className: 'gold' });
			ctx.invalidate();
		}
		function buildLoop() {
			disposeTree(dyn);
			dyn.clear();
			for (const l of labels) l.remove();
			labels = [];
			beads = [];
			const s = sim;
			const lc = new THREE.CatmullRomCurve3(s.lp.map(v3), true, 'centripetal');
			dyn.add(glowTube(lc, { color: 'teal', closed: true, radius: 0.028, segments: 300 }));
			for (let k = 0; k < 3; k++) {
				const b = glowPoint([0, 0, 0], { color: 'teal', size: 0.028, halo: 7 });
				dyn.add(b);
				beads.push({ obj: b, phase: k / 3 });
			}
			for (const p of s.pierce) {
				dyn.add(glowPoint(v3(p.p), { color: 'rose', size: 0.04, halo: 9 }));
				labels.push(ctx.label(v3([p.p[0], p.p[1] + 0.22, p.p[2]]), p.sign > 0 ? '+1' : '−1', { className: 'rose sign3d' }));
			}
			const gp = s.loop(0.25);
			labels.push(ctx.label(v3([gp[0], gp[1] + 0.2, gp[2]]), tex('\\gamma'), { className: 'teal' }));
			placeBeads(time);
			ctx.invalidate();
		}
		let time = 0;
		function placeBeads(t: number) {
			for (const b of beads) {
				const u = frac(b.phase + t * 0.12 * anim);
				b.obj.position.copy(v3(sim.loop(u)));
			}
		}
		const fit = fovFitter(ctx.camera, 40);
		const off = ctx.onFrame((t) => {
			time = t;
			fit();
			placeBeads(t);
		});
		api = { knot: buildKnot, loop: buildLoop };
		buildKnot();
		buildLoop();

		// ── grab the loop and drag it along the knot ──
		const screen = (p: V3) => ctx.project(v3(p));
		const pointer = (e: PointerEvent) => {
			const r = canvas.getBoundingClientRect();
			return { x: e.clientX - r.left, y: e.clientY - r.top };
		};
		const onLoop = (e: PointerEvent) => {
			const q = pointer(e);
			return sim.lp.some((p) => {
				const s = screen(p);
				return Math.hypot(s.x - q.x, s.y - q.y) < 14;
			});
		};
		// the pointer's offset from the knot point the loop is on, so it does not jump when grabbed
		let grab: { dx: number; dy: number } | null = null;
		let controlsWere = true;
		let spinWas = false;
		const onDown = (e: PointerEvent) => {
			if (e.button !== 0 || !onLoop(e)) return;
			const q = pointer(e);
			const k = screen(sim.K(t0));
			grab = { dx: q.x - k.x, dy: q.y - k.y };
			controlsWere = controls?.enabled ?? false;
			spinWas = controls?.autoRotate ?? false;
			if (controls) {
				controls.enabled = false;
				controls.autoRotate = false;
			}
			canvas.setPointerCapture(e.pointerId);
			canvas.style.cursor = 'grabbing';
		};
		const onMove = (e: PointerEvent) => {
			if (!grab) {
				if (e.pointerType === 'mouse') canvas.style.cursor = onLoop(e) ? 'grab' : '';
				return;
			}
			const q = pointer(e);
			const x = q.x - grab.dx;
			const y = q.y - grab.dy;
			// search only near where the loop is, so it follows the strand through the knot's crossings
			const n = sim.pts.length;
			const i0 = Math.round(t0 * n);
			let best = i0;
			let bd = Infinity;
			for (let di = -40; di <= 40; di++) {
				const i = (((i0 + di) % n) + n) % n;
				const s = screen(sim.pts[i]);
				const d = Math.hypot(s.x - x, s.y - y);
				if (d < bd) ((bd = d), (best = i));
			}
			t0 = best / n;
		};
		const onUp = () => {
			if (!grab) return;
			grab = null;
			if (controls) {
				controls.enabled = controlsWere;
				controls.autoRotate = spinWas;
			}
			canvas.style.cursor = '';
		};
		// capture phase: runs before OrbitControls, which then finds itself disabled
		canvas.addEventListener('pointerdown', onDown, { capture: true });
		canvas.addEventListener('pointermove', onMove);
		canvas.addEventListener('pointerup', onUp);
		canvas.addEventListener('pointercancel', onUp);
		return {
			dispose() {
				off();
				api = null;
				knotLabel?.remove();
				for (const l of labels) l.remove();
				canvas.removeEventListener('pointerdown', onDown, { capture: true });
				canvas.removeEventListener('pointermove', onMove);
				canvas.removeEventListener('pointerup', onUp);
				canvas.removeEventListener('pointercancel', onUp);
			}
		};
	}

	$effect(() => {
		void knot;
		untrack(() => api?.knot());
	});
	$effect(() => {
		void sim;
		api?.loop();
	});

	// arrow keys move the loop along the knot
	function key(e: KeyboardEvent) {
		const k = ({ ArrowRight: 1, ArrowUp: 1, ArrowLeft: -1, ArrowDown: -1 } as Record<string, number>)[e.key];
		if (!k) return;
		e.preventDefault();
		t0 = frac(t0 + (e.shiftKey ? 0.05 : 0.01) * k);
	}

	const multiple = (n: number) => (n === 0 ? '0' : n === 1 ? '[m]' : n === -1 ? '-[m]' : `${n}\\,[m]`);
	const classTeX = $derived(`[\\gamma] = ${multiple(lkInt)} \\ \\in\\ H_1(\\R^3\\setminus K)\\cong\\Z`);
</script>

<div class="kl">
	<div class="stage">
		<Scene3D
			{setup}
			height={430}
			animate
			camera={{ position: [0, 2.35, 4.1], fov: 40 }}
			controls={{ autoRotate: true, autoRotateSpeed: 0.4 }}
			label="A glowing gold knot (a trefoil or a round circle) with a thin teal loop near it that can be dragged along the knot. The loop goes once or twice around the knot's strand, or sits beside it without linking. For the round circle, a glassy disk spans it and rose points mark where the loop pierces the disk."
		/>
		<!-- the keyboard way to move the loop: focus the picture and use the arrow keys -->
		<div
			class="keys"
			role="slider"
			tabindex="0"
			aria-label="The loop γ: arrow keys move it along the knot"
			aria-valuemin={0}
			aria-valuemax={99}
			aria-valuenow={Math.round(t0 * 100)}
			aria-valuetext="{Math.round(t0 * 100)}% of the way along the knot; linking number {lkInt}"
			onkeydown={key}
		></div>
	</div>
	<div class="read ui" aria-live="polite">
		<div class="row"><span class="k">Gauss linking integral</span><TeX tex={`\\mathrm{lk}(\\gamma, K) = ${sim.lk.toFixed(3)}`} /></div>
		<div class="row"><span class="k">class of the loop</span><TeX tex={classTeX} /></div>
		{#if knot === 'unknot'}
			<div class="row">
				<span class="k">piercings of the disk</span><TeX
					tex={sim.pierce.length ? sim.pierce.map((p) => (p.sign > 0 ? '(+1)' : '(-1)')).join('+') + ` = ${sim.pierce.reduce((a, p) => a + p.sign, 0)}` : '\\text{none} \\Rightarrow 0'}
				/>
			</div>
		{/if}
	</div>
	<div class="ctl ui">
		<Segmented
			bind:value={knot}
			label="Which knot"
			options={[
				{ value: 'trefoil', label: 'Trefoil' },
				{ value: 'unknot', label: 'Unknot (with a disk)' }
			]}
		/>
		<Segmented
			bind:value={kind}
			label="Which loop"
			options={[
				{ value: 'meridian', label: 'once around' },
				{ value: 'double', label: 'twice around' },
				{ value: 'far', label: 'not linked' }
			]}
		/>
	</div>
</div>

<style>
	.kl :global(.lbl3d.sign3d) {
		font-family: var(--font-ui);
		font-weight: 700;
		font-size: 0.78rem;
		padding: 0.05rem 0.4rem;
		border-radius: 999px;
		background: rgba(20, 8, 16, 0.72);
		border: 1px solid rgba(242, 141, 182, 0.55);
		text-shadow: none;
	}
	.stage {
		position: relative;
	}
	.keys {
		position: absolute;
		inset: 0;
		pointer-events: none;
		outline: none;
	}
	.keys:focus-visible {
		outline: 2px solid var(--gold-bright);
		outline-offset: -4px;
	}
	.read {
		display: grid;
		gap: 0.3rem;
		padding: 0.7rem 1.2rem 0.6rem;
		border-top: 1px solid var(--line-faint);
		color: var(--ink-bright);
		font-size: 0.95rem;
	}
	.row {
		display: flex;
		flex-wrap: wrap;
		align-items: baseline;
		gap: 0.2rem 0.9rem;
	}
	.k {
		min-width: 11rem;
		font-size: 0.66rem;
		letter-spacing: 0.12em;
		text-transform: uppercase;
		color: var(--ink-faint);
	}
	.ctl {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: 0.7rem 1.2rem;
		padding: 0.85rem 1.2rem 1rem;
		border-top: 1px solid var(--line-faint);
		background: rgba(5, 8, 16, 0.45);
	}
</style>
