import type { GlossaryEntry } from './types';

const chapter = 'big-picture/homological-algebra';

export const entries: GlossaryEntry[] = [
	{
		key: 'category-of-chain-complexes',
		term: 'Category of chain complexes',
		def: 'The category \\(\\Ch\\) whose objects are chain complexes of abelian groups and whose arrows are chain maps. Homology is a functor \\(H_n\\colon\\Ch\\to\\Ab\\).',
		chapter,
		anchor: 'def-complex',
		see: ['chain-complex', 'chain-map', 'functor']
	},
	{
		key: 'chain-homotopy-equivalence',
		term: 'Chain homotopy equivalence',
		def: 'Chain maps \\(f\\colon C\\to D\\) and \\(g\\colon D\\to C\\) whose composites \\(g\\circ f\\) and \\(f\\circ g\\) are chain homotopic to the identities. Chain homotopy equivalent complexes have isomorphic homology.',
		chapter,
		anchor: 'def-chain-homotopy',
		see: ['chain-homotopy', 'homotopy-equivalence']
	},
	{
		key: 'snake-lemma',
		term: 'Snake lemma',
		def: 'For a commuting diagram with exact rows \\(A\\to B\\to C\\to 0\\) and \\(0\\to A\'\\to B\'\\to C\'\\) joined by vertical maps \\(a, b, c\\), there is a connecting homomorphism \\(\\delta\\colon\\ker c\\to\\coker a\\) making \\(\\ker a\\to\\ker b\\to\\ker c\\to\\coker a\\to\\coker b\\to\\coker c\\) exact.',
		chapter,
		anchor: 'lem-snake',
		see: ['connecting-homomorphism', 'diagram-chase', 'long-exact-sequence']
	},
	{
		key: 'tensor-product',
		term: 'Tensor product',
		def: 'The abelian group \\(A\\otimes B\\) generated by symbols \\(a\\otimes b\\) that add in each slot separately. For example \\(\\Z\\otimes G\\cong G\\), \\(\\Z/m\\otimes\\Z/n\\cong\\Z/\\gcd(m,n)\\) and \\(\\Z/n\\otimes\\Q = 0\\).',
		chapter,
		anchor: 'def-tensor',
		see: ['tor', 'right-exact']
	},
	{
		key: 'left-exact',
		term: 'Left exact',
		def: 'A functor is left exact if it turns each short exact sequence into a sequence that is exact except that its last map need not be onto. \\(\\Hom(-,G)\\) is left exact: \\(0\\to\\Hom(C,G)\\to\\Hom(B,G)\\to\\Hom(A,G)\\) is exact.',
		chapter,
		anchor: 'prop-exactness',
		see: ['right-exact', 'ext']
	},
	{
		key: 'right-exact',
		term: 'Right exact',
		def: 'A functor is right exact if it turns each short exact sequence into a sequence that is exact except that its first map need not be one-to-one. Tensoring is right exact: \\(A\\otimes G\\to B\\otimes G\\to C\\otimes G\\to 0\\) is exact.',
		chapter,
		anchor: 'prop-exactness',
		see: ['left-exact', 'tor']
	},
	{
		key: 'free-resolution',
		term: 'Free resolution',
		def: 'An exact sequence \\(\\cdots\\to F_2\\to F_1\\to F_0\\to A\\to 0\\) in which every \\(F_i\\) is free abelian. Every abelian group has one of length one, \\(0\\to F_1\\to F_0\\to A\\to 0\\): generators and the relations among them.',
		chapter,
		anchor: 'def-resolution',
		see: ['tor', 'ext', 'free-abelian-group']
	},
	{
		key: 'tor',
		term: 'Tor',
		def: '\\(\\Tor(A,G)\\) is the homology in degree 1 of \\(F_\\bullet\\otimes G\\), for a free resolution \\(F_\\bullet\\) of \\(A\\). It measures how tensoring with \\(G\\) fails to be exact: \\(\\Tor(\\Z/m,\\Z/n)\\cong\\Z/\\gcd(m,n)\\), and \\(\\Tor(A,G) = 0\\) if \\(A\\) or \\(G\\) is free.',
		chapter,
		anchor: 'def-tor-ext',
		see: ['tensor-product', 'ext', 'universal-coefficient-theorems']
	},
	{
		key: 'ext',
		term: 'Ext',
		def: '\\(\\Ext(A,G)\\) is the cohomology in degree 1 of \\(\\Hom(F_\\bullet,G)\\), for a free resolution \\(F_\\bullet\\) of \\(A\\). It measures how \\(\\Hom(-,G)\\) fails to be exact and classifies extensions: \\(\\Ext(\\Z/n,G)\\cong G/nG\\) and \\(\\Ext(\\Z,G) = 0\\).',
		chapter,
		anchor: 'def-tor-ext',
		see: ['tor', 'extension', 'universal-coefficient-theorems']
	},
	{
		key: 'extension',
		term: 'Extension',
		def: 'A short exact sequence \\(0\\to A\\to B\\to C\\to 0\\), viewed as a way of building \\(B\\) from a subgroup \\(A\\) and a quotient \\(C\\). For instance \\(\\Z/4\\) and \\(\\Z/2\\oplus\\Z/2\\) are both extensions of \\(\\Z/2\\) by \\(\\Z/2\\).',
		chapter,
		anchor: 'names',
		see: ['ext', 'short-exact-sequence']
	},
	{
		key: 'derived-functor',
		term: 'Derived functors',
		def: 'The functors obtained by applying a functor that is only partly exact to a resolution and taking homology: \\(\\Tor\\) comes from \\(\\otimes\\), \\(\\Ext\\) from \\(\\Hom\\), and sheaf cohomology from taking global sections. They record, degree by degree, how exactness fails.',
		chapter,
		anchor: 'derived-functors',
		see: ['tor', 'ext', 'sheaf-cohomology']
	},
	{
		key: 'universal-coefficient-theorems',
		term: 'Universal coefficient theorems',
		def: '\\(H_n(X;G)\\cong(H_n(X)\\otimes G)\\oplus\\Tor(H_{n-1}(X),G)\\) and \\(H^n(X;G)\\cong\\Hom(H_n(X),G)\\oplus\\Ext(H_{n-1}(X),G)\\). Integral homology determines (co)homology with any coefficients; the splittings exist but are not natural.',
		chapter,
		anchor: 'thm-uct',
		see: ['tor', 'ext']
	},
	{
		key: 'kunneth-theorem',
		term: 'Künneth theorem',
		def: 'For cell complexes, \\(H_n(X\\times Y)\\cong\\bigoplus_{i+j=n}H_i(X)\\otimes H_j(Y)\\;\\oplus\\bigoplus_{i+j=n-1}\\Tor(H_i(X),H_j(Y))\\): the homology of a product from the homology of its factors.',
		chapter,
		anchor: 'thm-kunneth',
		see: ['kunneth-formula', 'tensor-product', 'tor']
	},
	{
		key: 'filtered-complex',
		term: 'Filtered complex',
		def: 'A chain complex \\(C\\) with a nested sequence of subcomplexes \\(F_0C\\subseteq F_1C\\subseteq\\cdots\\subseteq C\\) — for example the chains of the skeleta of a cell complex. Its spectral sequence computes \\(H(C)\\) from the pieces \\(F_pC/F_{p-1}C\\).',
		chapter,
		anchor: 'spectral-sequences',
		see: ['spectral-sequence', 'filtration']
	},
	{
		key: 'spectral-sequence',
		term: 'Spectral sequence',
		def: 'A sequence of pages \\(E^1, E^2, \\dots\\) of groups \\(E^r_{p,q}\\) with differentials \\(d^r\\colon E^r_{p,q}\\to E^r_{p-r,q+r-1}\\), each page the homology of the one before, converging to the homology of a filtered complex. It computes homology in stages, each page correcting the last.',
		chapter,
		anchor: 'spectral-sequences',
		see: ['filtered-complex', 'serre-spectral-sequence']
	},
	{
		key: 'serre-spectral-sequence',
		term: 'Serre spectral sequence',
		def: 'For a fibration \\(F\\to E\\to B\\) with \\(B\\) simply connected, a spectral sequence with \\(E^2_{p,q} = H_p(B;H_q(F))\\) converging to \\(H_{p+q}(E)\\). Serre used it to prove that spheres have infinitely many nonzero homotopy groups.',
		chapter,
		anchor: 'spectral-sequences',
		see: ['spectral-sequence', 'homotopy-group']
	},
	{
		key: 'eilenberg-steenrod-axioms',
		term: 'Eilenberg–Steenrod axioms',
		def: 'Five axioms for a homology theory on pairs of spaces: homotopy invariance, a long exact sequence for every pair, excision, additivity, and the dimension axiom (a point has homology only in degree 0). On cell complexes they determine homology from the coefficient group.',
		chapter,
		anchor: 'def-homology-theory',
		see: ['homology-theory', 'dimension-axiom', 'coefficient-group']
	},
	{
		key: 'homology-theory',
		term: 'Homology theory',
		def: 'A sequence of functors \\(h_n\\) from pairs of spaces to abelian groups, with natural connecting maps \\(h_n(X,A)\\to h_{n-1}(A)\\), satisfying the Eilenberg–Steenrod axioms.',
		chapter,
		anchor: 'def-homology-theory',
		see: ['eilenberg-steenrod-axioms', 'generalized-cohomology-theory']
	},
	{
		key: 'coefficient-group',
		term: 'Coefficient group',
		def: 'The group \\(G = h_0(\\mathrm{pt})\\) that a homology theory assigns to a point. On cell complexes, ordinary homology with coefficients in \\(G\\) is the only theory satisfying all five axioms with that coefficient group.',
		chapter,
		anchor: 'def-homology-theory',
		see: ['eilenberg-steenrod-axioms']
	},
	{
		key: 'dimension-axiom',
		term: 'Dimension axiom',
		def: 'The Eilenberg–Steenrod axiom saying that a point has homology only in degree 0. Dropping it gives generalized homology and cohomology theories such as K-theory and cobordism.',
		chapter,
		anchor: 'def-homology-theory',
		see: ['eilenberg-steenrod-axioms', 'generalized-cohomology-theory']
	},
	{
		key: 'generalized-cohomology-theory',
		term: 'Generalized (co)homology theory',
		def: 'A theory satisfying every Eilenberg–Steenrod axiom except the dimension axiom, so that a point may have nonzero groups in many degrees. Examples: K-theory, cobordism, stable homotopy.',
		chapter,
		anchor: 'dropping-an-axiom',
		see: ['dimension-axiom', 'k-theory', 'cobordism', 'spectrum']
	}
];
