import type { GlossaryEntry } from './types';

const chapter = 'cohomology/de-rham';

export const entries: GlossaryEntry[] = [
	{
		key: 'closed-form',
		term: 'Closed form',
		def: 'A differential form \\(\\omega\\) with \\(d\\omega = 0\\). A closed 1-form in the plane is one with zero curl; its integral around every small loop that bounds a region is zero.',
		chapter,
		anchor: 'def-closed-exact',
		see: ['exact-form']
	},
	{
		key: 'exact-form',
		term: 'Exact form',
		def: 'A differential form that is the exterior derivative of another, \\(\\omega = d\\eta\\). Exact forms are closed, because \\(d\\circ d = 0\\); an exact 1-form has zero integral around every closed loop.',
		chapter,
		anchor: 'def-closed-exact',
		see: ['closed-form']
	},
	{
		key: 'de-rham-cohomology',
		term: 'de Rham cohomology',
		def: 'The vector space \\(H^k_{\\dR}(M)\\) of closed \\(k\\)-forms on \\(M\\) modulo exact ones: it measures how far closed forms are from being exact, which happens exactly when \\(M\\) has holes.',
		chapter,
		anchor: 'def-de-rham',
		see: ['closed-form', 'exact-form', 'de-rham-theorem']
	},
	{
		key: 'cohomologous',
		term: 'Cohomologous',
		def: 'Two closed forms are cohomologous if their difference is exact; they then define the same de Rham class \\([\\omega]\\).',
		chapter,
		anchor: 'def-de-rham'
	},
	{
		key: 'locally-constant-function',
		term: 'Locally constant function',
		def: 'A function that is constant near every point, so constant on each connected piece of its domain. These are the functions with \\(df = 0\\), and they form \\(H^0_{\\dR}(M) \\cong \\R^{\\#\\text{components}}\\).',
		chapter,
		anchor: 'h-zero'
	},
	{
		key: 'angle-form',
		term: 'Angle form',
		def: 'The 1-form \\(d\\theta = (-y\\,dx + x\\,dy)/(x^2+y^2)\\) on the punctured plane. It is closed but not exact: its integral around any loop is \\(2\\pi\\) times the loop’s winding number about the origin.',
		chapter,
		anchor: 'the-vortex',
		see: ['closed-form', 'punctured-plane']
	},
	{
		key: 'punctured-plane',
		term: 'Punctured plane',
		def: 'The plane with one point removed, \\(\\R^2\\setminus 0\\). It is homotopy equivalent to a circle, and \\(H^1_{\\dR}(\\R^2\\setminus 0)\\cong\\R\\), generated by the angle form.',
		chapter,
		anchor: 'the-vortex'
	},
	{
		key: 'multivalued-function',
		term: 'Multivalued function',
		def: 'An informal name for a rule like the angle \\(\\theta\\) of a point, which can be chosen continuously near each point but changes by a constant (here \\(2\\pi\\)) after a trip around a loop, so it is not a genuine function on the whole space.',
		chapter,
		anchor: 'staircase'
	},
	{
		key: 'star-shaped',
		term: 'Star-shaped region',
		def: 'A region \\(U\\) containing a point \\(c\\) such that the straight segment from \\(c\\) to every point of \\(U\\) stays inside \\(U\\). Convex regions are star-shaped; an annulus is not.',
		chapter,
		anchor: 'def-star'
	},
	{
		key: 'poincare-lemma',
		term: 'Poincaré lemma',
		def: 'On a star-shaped open subset of \\(\\R^n\\) every closed form of degree at least 1 is exact. A potential is built by integrating along the rays from the centre.',
		chapter,
		anchor: 'thm-poincare-lemma',
		see: ['star-shaped']
	},
	{
		key: 'de-rham-homotopy-invariance',
		term: 'Homotopy invariance (de Rham)',
		def: 'Homotopic smooth maps induce the same map on de Rham cohomology; hence homotopy-equivalent manifolds have isomorphic de Rham cohomology.',
		chapter,
		anchor: 'thm-homotopy'
	},
	{
		key: 'de-rham-mayer-vietoris',
		term: 'Mayer–Vietoris sequence (de Rham)',
		def: 'For a manifold covered by two open sets \\(U, V\\), a long exact sequence \\(\\cdots\\to H^k(U\\cup V)\\to H^k(U)\\oplus H^k(V)\\to H^k(U\\cap V)\\to H^{k+1}(U\\cup V)\\to\\cdots\\) that computes cohomology by cutting and pasting.',
		chapter,
		anchor: 'mayer-vietoris'
	},
	{
		key: 'period',
		term: 'Period',
		def: 'The integral \\(\\int_z \\omega\\) of a closed form over a cycle. By Stokes’ theorem it depends only on the cohomology class of \\(\\omega\\) and the homology class of \\(z\\); a closed form is exact exactly when all its periods vanish.',
		chapter,
		anchor: 'de-rhams-theorem'
	},
	{
		key: 'de-rham-map',
		term: 'Integration map (de Rham map)',
		def: 'The map that turns a \\(k\\)-form \\(\\omega\\) into the \\(k\\)-cochain \\(\\sigma \\mapsto \\int_\\sigma\\omega\\). By Stokes’ theorem it satisfies \\(\\int d\\omega = \\delta\\!\\int\\omega\\), so it sends closed forms to cocycles and exact forms to coboundaries.',
		chapter,
		anchor: 'de-rhams-theorem'
	},
	{
		key: 'de-rham-theorem',
		term: "de Rham's theorem",
		def: 'For every smooth manifold \\(M\\), integration over chains gives an isomorphism \\(H^k_{\\dR}(M)\\cong H^k(M;\\R)\\): the smooth and the combinatorial cohomology agree (with real coefficients).',
		chapter,
		anchor: 'thm-de-rham',
		see: ['de-rham-map']
	},
	{
		key: 'amperes-law',
		term: "Ampère's law",
		def: 'For a steady current \\(I\\), the circulation of the magnetic field around a loop is \\(\\mu_0 I\\) times the number of times the loop links the current. Outside a wire the field is closed but not exact.',
		chapter,
		anchor: 'physics'
	},
	{
		key: 'vector-potential',
		term: 'Vector potential',
		def: 'A field \\(\\mathbf A\\) with \\(\\mathbf B = \\operatorname{curl}\\mathbf A\\); as forms, a 1-form \\(A\\) with \\(B = dA\\). Outside a solenoid \\(B = 0\\), so \\(A\\) is closed — but it is not exact.',
		chapter,
		anchor: 'aharonov-bohm'
	},
	{
		key: 'aharonov-bohm-effect',
		term: 'Aharonov–Bohm effect',
		def: 'A quantum particle travelling around a solenoid acquires a phase \\(q\\Phi/\\hbar\\) per turn, although the magnetic field vanishes along its path: the phase measures the de Rham class of the vector potential.',
		chapter,
		anchor: 'aharonov-bohm'
	},
	{
		key: 'solid-angle-form',
		term: 'Solid-angle form',
		def: 'The 2-form \\(\\sigma = (x\\,dy\\wedge dz + y\\,dz\\wedge dx + z\\,dx\\wedge dy)/r^3\\) on \\(\\R^3\\setminus 0\\). It is closed, and \\(\\iint_{S^2}\\sigma = 4\\pi\\), so it is not exact: it generates \\(H^2_{\\dR}(\\R^3\\setminus 0)\\cong\\R\\).',
		chapter,
		anchor: 'gauss'
	},
	{
		key: 'gauss-law',
		term: "Gauss's law",
		def: 'The electric flux out of a closed surface is the enclosed charge divided by \\(\\varepsilon_0\\). For a point charge the field is a multiple of the solid-angle form, and the flux counts how often the surface wraps around the charge.',
		chapter,
		anchor: 'gauss'
	}
];
