import type { GlossaryEntry } from './types';

const chapter = 'cohomology/cup-product';

export const entries: GlossaryEntry[] = [
	{
		key: 'cup-product',
		term: 'Cup product',
		def: 'The product of cochains, “front face times back face”: \\((\\varphi\\smile\\psi)([v_0,\\dots,v_{p+q}]) = \\varphi([v_0,\\dots,v_p])\\,\\psi([v_p,\\dots,v_{p+q}])\\). It passes to cohomology and makes \\(H^*(X)\\) a ring.',
		chapter,
		anchor: 'def-cup',
		see: ['front-face', 'back-face', 'cohomology-ring']
	},
	{
		key: 'front-face',
		term: 'Front face',
		def: 'For an ordered simplex \\([v_0,\\dots,v_{p+q}]\\), the face \\([v_0,\\dots,v_p]\\) made of its first vertices. In \\(\\varphi\\smile\\psi\\) the left factor \\(\\varphi\\) is read on the front face.',
		chapter,
		anchor: 'def-cup',
		see: ['back-face', 'cup-product']
	},
	{
		key: 'back-face',
		term: 'Back face',
		def: 'For an ordered simplex \\([v_0,\\dots,v_{p+q}]\\), the face \\([v_p,\\dots,v_{p+q}]\\) made of its last vertices. It shares exactly one vertex, \\(v_p\\), with the front face. The right factor of a cup product is read on it.',
		chapter,
		anchor: 'def-cup',
		see: ['front-face', 'cup-product']
	},
	{
		key: 'leibniz-rule',
		term: 'Leibniz rule (for the cup product)',
		def: 'The formula \\(\\delta(\\varphi\\smile\\psi) = \\delta\\varphi\\smile\\psi + (-1)^p\\varphi\\smile\\delta\\psi\\) for a \\(p\\)-cochain \\(\\varphi\\) — the twin of \\(d(\\alpha\\wedge\\beta)=d\\alpha\\wedge\\beta+(-1)^k\\alpha\\wedge d\\beta\\). It is why cocycles multiply to cocycles.',
		chapter,
		anchor: 'leibniz-rule',
		see: ['cup-product']
	},
	{
		key: 'ring',
		term: 'Ring',
		def: 'An abelian group with an associative multiplication that distributes over addition and has a unit \\(1\\). Examples: \\(\\Z\\), \\(\\Z/n\\), polynomials, functions on a set, square matrices.',
		chapter,
		anchor: 'def-ring',
		see: ['commutative-ring', 'graded-ring']
	},
	{
		key: 'commutative-ring',
		term: 'Commutative ring',
		def: 'A ring in which \\(ab = ba\\) for all elements. \\(\\Z\\), \\(\\Z/2\\), \\(\\Q\\) and \\(\\R\\) are commutative rings, and serve as coefficients for cohomology rings.',
		chapter,
		anchor: 'def-ring',
		see: ['ring']
	},
	{
		key: 'unit-element',
		term: 'Unit (of a ring)',
		def: 'The element \\(1\\) with \\(1a = a = a1\\) for all \\(a\\). In a cohomology ring it is the class of the constant function \\(1\\) in \\(H^0\\).',
		chapter,
		anchor: 'def-ring',
		see: ['ring']
	},
	{
		key: 'graded-ring',
		term: 'Graded ring',
		def: 'A ring split into pieces \\(R^0\\oplus R^1\\oplus R^2\\oplus\\cdots\\) so that a product of an element of \\(R^p\\) and one of \\(R^q\\) lies in \\(R^{p+q}\\): degrees add when you multiply.',
		chapter,
		anchor: 'def-cohomology-ring',
		see: ['cohomology-ring', 'degree-of-a-class']
	},
	{
		key: 'cohomology-ring',
		term: 'Cohomology ring',
		def: 'The direct sum \\(H^*(X;R)=H^0\\oplus H^1\\oplus H^2\\oplus\\cdots\\) with the cup product as multiplication. It is an invariant of homotopy type, much sharper than the groups alone.',
		chapter,
		anchor: 'def-cohomology-ring',
		see: ['cup-product', 'graded-ring']
	},
	{
		key: 'degree-of-a-class',
		term: 'Degree (of a cohomology class)',
		def: 'A class in \\(H^p\\) has degree \\(p\\), written \\(|\\alpha| = p\\). Degrees add under the cup product.',
		chapter,
		see: ['graded-ring']
	},
	{
		key: 'ring-homomorphism',
		term: 'Ring homomorphism',
		def: 'A map between rings that preserves sums, products and the unit. A continuous map \\(f\\colon X\\to Y\\) induces a ring homomorphism \\(f^*\\colon H^*(Y)\\to H^*(X)\\), with \\(f^*(\\alpha\\smile\\beta) = f^*\\alpha\\smile f^*\\beta\\).',
		chapter,
		see: ['cohomology-ring']
	},
	{
		key: 'graded-commutativity',
		term: 'Graded commutativity',
		def: 'The rule \\(\\alpha\\smile\\beta = (-1)^{pq}\\,\\beta\\smile\\alpha\\) for cohomology classes of degrees \\(p\\) and \\(q\\). It holds for classes, not for cochains; over \\(\\Z/2\\) the sign disappears.',
		chapter,
		anchor: 'graded',
		see: ['cup-product', 'cup-square']
	},
	{
		key: 'exterior-algebra',
		term: 'Exterior algebra',
		def: 'The ring generated by elements that anticommute and square to zero, like \\(dx, dy\\). The cohomology ring of the torus is the exterior algebra \\(\\Lambda[\\alpha,\\beta]\\); that of \\(T^n\\) is the exterior algebra on \\(n\\) generators.',
		chapter,
		anchor: 'torus',
		see: ['cohomology-ring']
	},
	{
		key: 'truncated-polynomial-ring',
		term: 'Truncated polynomial ring',
		def: '\\(R[x]/(x^{n+1})\\): polynomials in \\(x\\) in which \\(x^{n+1}\\) and higher powers are set to \\(0\\). Examples: \\(H^*(\\RP^n;\\Z/2)=\\Z/2[x]/(x^{n+1})\\) and \\(H^*(\\CP^n;\\Z)=\\Z[x]/(x^{n+1})\\).',
		chapter,
		anchor: 'projective-spaces',
		see: ['cohomology-ring']
	},
	{
		key: 'fence',
		term: 'Fence (of a 1-cocycle)',
		def: 'A curve drawn on a triangulated surface across its edges, with a direction in which crossing it counts \\(+1\\). Counting crossings edge by edge gives a 1-cocycle; cup products of such classes count the crossings of their fences.',
		chapter,
		anchor: 'fences',
		see: ['push-off', 'cup-product']
	},
	{
		key: 'push-off',
		term: 'Push-off',
		def: 'A copy of a curve moved slightly to one side. The square \\(\\alpha\\smile\\alpha\\) of a class on a surface counts the crossings of its fence with a push-off; on a torus a push-off never crosses, on \\(\\RP^2\\) it must cross once.',
		chapter,
		anchor: 'mod-two',
		see: ['fence', 'cup-square']
	},
	{
		key: 'cup-square',
		term: 'Cup square',
		def: 'The product \\(\\alpha\\smile\\alpha\\) of a class with itself. Over \\(\\Z\\) odd-degree classes on orientable surfaces square to zero; over \\(\\Z/2\\) squares can survive, as on \\(\\RP^2\\) and the Klein bottle.',
		chapter,
		anchor: 'mod-two',
		see: ['graded-commutativity', 'push-off']
	},
	{
		key: 'cup-form',
		term: 'Cup product table (cup form)',
		def: 'For a surface, the table of products \\(\\ip{x_i\\smile x_j}{[M]}\\) of a basis of degree-1 classes. Mod 2 the torus has \\(\\left(\\begin{smallmatrix}0&1\\\\1&0\\end{smallmatrix}\\right)\\) and the Klein bottle \\(\\left(\\begin{smallmatrix}0&1\\\\1&1\\end{smallmatrix}\\right)\\).',
		chapter,
		anchor: 'klein',
		see: ['cup-product', 'cup-square']
	},
	{
		key: 'diagonal-map',
		term: 'Diagonal map',
		def: 'The map \\(X\\to X\\times X\\), \\(x\\mapsto(x,x)\\). Every space has one; pulling measurements back along it is what lets cohomology multiply.',
		chapter,
		anchor: 'multiplying',
		see: ['cup-product']
	},
	{
		key: 'cross-product',
		term: 'Cross product (in cohomology)',
		def: 'For classes \\(a\\) on \\(X\\) and \\(b\\) on \\(Y\\), the class \\(a\\times b = p_1^*a\\smile p_2^*b\\) on \\(X\\times Y\\), where \\(p_1,p_2\\) are the projections.',
		chapter,
		anchor: 'kunneth',
		see: ['kunneth-formula']
	},
	{
		key: 'kunneth-formula',
		term: 'Künneth formula',
		def: 'With field coefficients (and finitely many cells), the cohomology ring of a product is \\(H^*(X\\times Y)\\cong H^*(X)\\otimes H^*(Y)\\): its classes are products of classes of the factors, degrees adding. For example \\(b_k(T^n)=\\binom nk\\).',
		chapter,
		anchor: 'kunneth',
		see: ['cross-product']
	},
	{
		key: 'complex-projective-space',
		term: 'Complex projective space',
		def: '\\(\\CP^n\\), the space of complex lines through the origin in \\(\\C^{n+1}\\); it has real dimension \\(2n\\) and cohomology ring \\(\\Z[x]/(x^{n+1})\\) with \\(|x|=2\\).',
		chapter,
		anchor: 'projective-spaces',
		see: ['truncated-polynomial-ring']
	}
];
